ALTER TABLE tbcliente ADD primary key (CPF);

ALTER TABLE tbcliente ADD column (DATA_NASC DATE);

INSERT INTO tbcliente (
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASC)
VALUES ('37685412595', 'VALTER JOSE ALVES', 'AV. PINHEIRO WILSON', '', 'JOSE MENINO', 'CUBATAO', 'SÃO PAULO', '22542000', '30', 'M', 1200.00, 800.00, 0, '1990-10-15');

SELECT * FROM tbcliente;