/* SEÇÃO 18 - APRENDEU? SAIU O SISTEMA DO SEU JOSE

EXERCICIO DE FIXAÇÃO

1) CRIAR UM BANCO DE DADOS CHAMADO PROJETO OFICINA E CONECTE-SE AO BANCO
2) FAÇA A SEGUINTE MODELAGEM:
SR JOSÉ QUER MODERNIZAR SUA OFICINA E, POR ENQUANTO, CADASTRAR OS CARROS QUE ENTRAM
PARA REALIZAR SERVIÇOS E SEUS RESPECTIVOS DONOS.SR JOSE MENCIONOU QUE CADA CLIENTE
POSSUI APENAS UM CARRO.UM CARRO POSSUI UMA MARCA. SR JOSE TAMBÉM QUER SABER AS 
CORES DOS CARROS PARA TER IDEIA DE QUAL TINTA COMPRAR E, INFORMA QUE UM CARRO PODE TER
MAIS DE UMA COR. SR JOSE NECESSITA ARMAZENAR OS TELEFONES DOS CLIENTES, MAS NÃO QUER
QUE ELES SEJAM OBRIGATÓRIOS*/

CREATE DATABASE PROJETO_OFICINA;

USE PROJETO_OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT 
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);


CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO,ID_COR) # A PRIMARY KEY TORNA-SE A UNIÃO DAS DUAS CHAVES, ENTÃO EU POSSO CADASTRAR A UNIÃO 3 E 5 APENAS UMA VEZ, MAS POSSO USAR CADA ITEM DESSA UNIÃO EM OUTRAS COMBINAÇÕES COMO 1 E 5 OU 3 E 1.
);

/* CONSTRAINTS */

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);


ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


/* PREENCHER O BANCO COM NO MINIMO 10 CLIENTES */
INSERT INTO MARCA VALUES(NULL, 'RENAULT');
INSERT INTO CARRO VALUES(NULL, 'SANDERO','JEZ1980', 1);
INSERT INTO CLIENTE VALUES(NULL, 'JOAO EDUARDO', 'M', 2);
INSERT INTO COR VALUES(NULL, 'PRATA');
INSERT INTO COR VALUES(NULL, 'PRETO');
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '999257863', 4);
INSERT INTO CARRO_COR VALUES(2, 1);

INSERT INTO MARCA VALUES(NULL, 'FIAT');
INSERT INTO CARRO VALUES(NULL, 'PALIO','NAT1990', 2);
INSERT INTO CLIENTE VALUES(NULL, 'NATALIA', 'F', 3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '99998546', 5);
INSERT INTO CARRO_COR VALUES(3, 2);
