/* SEÇÃO 9: JUNTANDO AS PEÇAS */

/* SELEÇÃO, PROJEÇÃO E JUNÇÃO 

PROJEÇÃO =  TUDO AQUILO QUE QUEREMOS VER NA TELA
SELEÇÃO =  FILTRAR, OU FAZER UM SUBCONJUNTO DE UM CONJUNTO TOTAL DE REGISTROS DE UMA TABELA E A CLAUSULA DE SELEÇÃO É O WHERE
JUNÇÃO = 

EXEMPLOS:
SELECT NOME, SEXO, BAIRRO, CIDADE # PROJEÇÃO
FROM CLIENTE # ORIGEM
INNER JOIN ENDERECO ON ID_CLIENTE = FK_CLIENTE #JUNÇÃO
WHERE SEXO = 'F' # SELEÇÃO
*/

USE COMERCIO;

SELECT NOME, SEXO, BAIRRO, CIDADE # PROJEÇÃO
FROM CLIENTE # ORIGEM
INNER JOIN ENDERECO ON ID_CLIENTE = FK_CLIENTE #JUNÇÃO
WHERE SEXO = 'F'; # SELEÇÃO


SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE ON ID_CLIENTE = FK_CLIENTE;


SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO 
ON  CLIENTE.ID_CLIENTE = ENDERECO.FK_CLIENTE 
INNER JOIN TELEFONE 
ON CLIENTE.ID_CLIENTE = TELEFONE.FK_CLIENTE;



SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON  C.ID_CLIENTE = E.FK_CLIENTE 
INNER JOIN TELEFONE T
ON C.ID_CLIENTE = T.FK_CLIENTE;


/* SQL É UMA LINGUAGEM DE QUARTA GERAÇÃO, OU SEJA, LINGUAGEM SIMILAR A LINGUAGEM HUMANA
E ELA TEM CATEGORIAS:
	DML = DATA MANIPULATION LANGUANGE
		INSERT, SELECT, UPDATE, DELETE
    DDL = DATA DEFINITION LANGUAGE
		CREATE, TRUNCATE, ALTER, DROP
    DCL = DATA CONTROL LANGUAGE
		REVOKE, GRANT
    TCL = TRANSACTION CONTROL LANGUAGE
		COMMIT, ROLLBACK, SAVEPOINT
    
*/


SELECT * FROM CLIENTE
WHERE SEXO = 'M';

SELECT * FROM CLIENTE
WHERE ID_CLIENTE = 6;

UPDATE CLIENTE 
SET SEXO = 'F'
WHERE ID_CLIENTE = 6;

ALTER TABLE CLIENTE
CHANGE EMAIL E_MAIL VARCHAR(30) NOT NULL;


ALTER TABLE CLIENTE
MODIFY E_MAIL VARCHAR(40) NOT NULL;

/* DICA: USAR O CHANGE PARA TROCAR NOME DA COLUNA E MODIFY PARA ALTERAR O TIPO*/

ALTER TABLE CLIENTE
ADD RG VARCHAR(10) NOT NULL;

ALTER TABLE CLIENTE
DROP COLUMN RG;















