/* SEÇÃO 16: ORGANIZANDO A CASA - O DICIONÁRIO DE DADOS */

/* ALTERANOD TABELAS */

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

/* CREATE TABLE TABELA(
	COLUNA1 INT PRIMARY KEY AUTO_INCREMENT
);*/

/* ADICIONANDO UMA PK*/
ALTER TABLE TABELA 
ADD PRIMARY KEY (COLUNA1);

/* UM PONTO A SE OBSERVAR É QUE SE FAZEMOS A INCLUSÃO DA PK POR FORA, NÃO HA COMO ATRIBUIR O AUTO INCREMENTO */

/*ADICIONANDO COLUNA SEM POSICAO. ULTIMA POSICAO*/
ALTER TABLE TABELA 
ADD COLUNA varchar(30);

ALTER TABLE TABELA 
ADD COLUNA100 INT;

/* ADICIONANDO UMA COLUNA COM POSICAO*/
ALTER TABLE TABELA 
ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3;

/*MODIFICANDO O TIPO DE UM CAMPO*/
ALTER TABLE TABELA
 MODIFY COLUNA2 DATE NOT NULL;

/* RENOMEANDO O NOME DA TABELA*/ 
ALTER TABLE TABELA 
RENAME PESSOA;

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

/* Foreign key */
ALTER TABLE TIME 
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/* VERIFICAR AS CHAVES */
SHOW CREATE TABLE TIME;

/* A34 - ORGANIZACAO DE CHAVES - CONSTRAINT (REGRA) */

CREATE TABLE JOGADOR(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

CREATE TABLE TIMES(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	NOMETIME VARCHAR(30),
	ID_JOGADOR INT,
	FOREIGN KEY(ID_JOGADOR)
	REFERENCES JOGADOR(IDJOGADOR)
);

INSERT INTO JOGADOR VALUES(NULL,'GUERRERO');
INSERT INTO TIMES VALUES(NULL,'FLAMENGO',1);

SHOW CREATE TABLE JOGADOR;
SHOW CREATE TABLE TIMES;

/* PODEMOS OBSERVAR QUE O BANCO DEU UM NOME A NOSSA CONSTRAINT AUTOMATICAMENTE, MAS ISSO NÃO É UMA BOA PRÁTICA!

DIFERENTEMENTE DE ATRIBUIR UMA PK POR FORA, É UMA BOA PRATICA ATRIBUIR A CONSTRAINT POR FORA, ASSIM ATRIBUIMOS NOMES

MAS O MYSQL HÁ UMA LIMITAÇÃO QUANTO AO AUTO INCREMENT, ENTÃO UMA SOLUÇÃO É A PK COM AUTOINCREMENTO SER CRIADA POR DENTRO E AS DEMAIS REGRAS POR FORA - 
SOMENTE NO MYSQL OUTROS BANCOS PODEMOS FAZER TUDO POR FORA */

/* A35 - ORGANIZANDO CHAVES */
USE COMERCIO;
SHOW TABLES;

DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

SHOW CREATE TABLE TELEFONE;

/* DICIONARIO DE DADOS

ELE É UM METADADO, OU SEJAM ELE GUARDA O DADO DOS DADOS */

SHOW DATABASES;

USE INFORMATION_SCHEMA;

STATUS

SHOW TABLES;

DESC TABLE_CONSTRAINTS;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
	   TABLE_NAME AS "TABELA",
	   CONSTRAINT_NAME AS "NOME REGRA",
	   CONSTRAINT_TYPE AS "TIPO"
	   FROM TABLE_CONSTRAINTS
	   WHERE CONSTRAINT_SCHEMA = 'COMERCIO';

/* APAGANDO CONSTRAINTS */

USE COMERCIO;

ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE;

	ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);