desc tb_cliente;

insert into tb_cliente values ('NATALIA', 'NATALIA', null, 'NSFOLIVEIRA!GMAIL.COM', 'AV PRESIDENTE WILSON', '991260846', 'F');

insert into tb_cliente(NOME, NOME_SOCIAL, CPF, EMAIL, ENDERECO, TELEFONE, SEXO) values ('LILIAN', 'LILIAN', NULL, 'LILIAN@GMAIL.COM', 'AV AVENIDA', '991284685', 'F');

insert into tb_cliente values ('MARCO', 'MARCO', NULL, 'MARCO@GMAIL.COM', 'AV PRESIDENTE WILSON', '9758528425', 'M'),
							  ('ANDRIELLE', 'ANDRIELLE', NULL, 'ANDRIELLE!GMAIL.COM', 'AV GUASSU', '34961715', 'F');