/*SEÇÃO 21 - PROGRAME, PROGRAME!*/

/*86. INTRODUÇÃO AOS CURSORES

UM VETOR É UMA COLEÇÃO DE DADOS DO MESMO TIPO E SUA REPRESENTAÇÃO GRÁFICA SÃO DOIS COLCHETES [], ASSIM COMO LISTAS EM ALGUMAS LINGUAGENS.
UM CURSOR NADA MAIS É QUE UM VETOR. EM SQL PODEMOS FAZER USO DOS CURSORES, MAS DEVEMOS USAR COM MODERAÇÃO, POIS */

CREATE DATABASE AULA_CURSORES;
USE AULA_CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL,'MAFRA',32432,242334,574545);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA',65465,65443,653454);
INSERT INTO VENDEDORES VALUES(NULL,'JOAO',12432,65356,8756);
INSERT INTO VENDEDORES VALUES(NULL,'LILIAN',4567,9676,8765);
INSERT INTO VENDEDORES VALUES(NULL,'ANTONIO',3467,68756,99765);
INSERT INTO VENDEDORES VALUES(NULL,'GLORIA',54786,76889,7098);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;
/*LEMBRANDO QUE OS CALCULOS ACIMA SÃO REALIZADOS EM TEMPO DE EXECUÇÃO, ENTÃO DEPENDENDO PODE COMPROMETER O PROCESSAMENTO E DEIXAR O BANCO LENDO*/

/*87, E MAIS CURSORES*/

CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

-- COMO VAMOS PROGRAMAR, A PRIMEIRA COISA QUE FAZEMOS É MUDAR O CURSOS!
DELIMITER $ 

-- NESSE PROCEDIMENTO VEREMOS COMO PODEMOS FAZER DECLARAÇÃO DE VARIÁVEIS
CREATE PROCEDURE INSEREDADOS()
BEGIN
		DECLARE FIM INT DEFAULT 0; # NESSA VARIÁVEL ATRIBUIMOS QUE SEU VALOR INCIAL É 0
		DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT; # VARIÁVEIS PARA GUARDAR OS MESES E OS CALCULOS DE SOMA E MEDIA
		DECLARE VNOME VARCHAR(50);
		#ABAIXO VEMOS COMO DECLARAR O VETOR (NAO PRECISAMOS DECLARAR O TAMANHO DO CURSOR
		DECLARE REG CURSOR FOR(
			#ABAIXO INDICAMOS O QUE QUEREMOS ARMAZENAR NESSE VETOR
			SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
		);
		#A VARIAVEL ABAIXO É PADRÃO. ELA É O 'ROBOZINHO' QUE OLHA PRO NOSSO VETOR E PARA O LOOP QUANDO TERMINAM OS REGISTROS. É UMA VARIAVEL DE MANIPULACAO CONTINUA
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
		#O OPEN PEGARÁ O RESULTADO DA QUERY REG QUE FIZEMOS NO CURSOR E JOGARÁ NA MEMÓRIA RAM
		OPEN REG;
		#COM OS DADOS NA MEMORIA RAM, VAMOS INICIAR NOSSO LOOP
		REPEAT
			#O COMANDO FETCH DIZ 'ME TRAGA O PROXIMO REGISTRO DO CURSOR' E COM ISSO FARÁ O QUE DEFINIRMOS.
			FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
			IF NOT FIM THEN
			
				SET VTOTAL = VAR1 + VAR2 + VAR3;
				SET VMEDIA = VTOTAL / 3;
				
				INSERT INTO VEND_TOTAL VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);
				
			END IF;
			
		UNTIL FIM END REPEAT;
		#COMO ABRIMOS O REGISTRO COM O COMANDO OPEN E INSERIMOS ELMENTOS NA MEMORIA RAM, QUANDO TERMINAMOS PRECISAMOS LIMPA-LA
		CLOSE REG;
END
$

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

DELIMITER ;

CALL INSEREDADOS();

INSERT INTO VENDEDORES VALUES(NULL,'LETICIA',656,3546,234545);
INSERT INTO VENDEDORES VALUES(NULL,'CELIA',6766,56556,65454);

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

DELETE FROM VEND_TOTAL;

CALL INSEREDADOS();

