/* SEÇÃO 8: Modelando Bancos de Dados para Sistema */

/* PRIMEIRA FORMA NORMAL 

REGRA 01: TODO CAMPO VETORIZADO SE TORNARA A OUTRA TABELA
EX: TEÇEFPME

REGRA 02: TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA (OU QUANDO O CAMPO FOR DIVISIVEL)
EX ENDEREÇO

REGRA 03: TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO UNIDCO! (CHAVE PRIMARIA - PRIMARY KEY)
EX ID

*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

/* REGRAS DE NEGOCIOS
ENDEREÇO - OBRIGATORIO -  CADASTRI DE SOMENTE UM;
TELEFONE - OPCIONAL - CADASTRO DE MAIS DE UM */

/* OBSERVAÇÃ
1X1 - EM RELACIONAMENTOS UM PARA A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA
1XN - EM RELACIONAMENTO UM PARA N A CHAVE ESTRANGEIRA FICARÁ NA CARDINALIDADE N*/


CREATE TABLE CLIENTE(
	ID_CLIENTE	INT PRIMARY KEY AUTO_INCREMENT,
	NOME		VARCHAR(30) NOT NULL,
    SEXO		ENUM('M','F') NOT NULL,
    EMAIL		VARCHAR(30) UNIQUE NOT NULL,
    CPF			VARCHAR(30) UNIQUE NOT NULL    
);

SHOW DATABASES;

CREATE TABLE ENDERECO(

	ID_ENDERECO	INT PRIMARY KEY AUTO_INCREMENT,
    RUA			VARCHAR(30) NOT NULL,
    BAIRRO		VARCHAR(20) NOT NULL,
    CIDADE		VARCHAR(20) NOT NULL,
    ESTADO		CHAR(2) NOT NULL,
    FK_CLIENTE	INT UNIQUE,
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)    
);

CREATE TABLE TELEFONE (
	ID_TELEFONE	INT PRIMARY KEY AUTO_INCREMENT,
	TIPO		ENUM('COM', 'RES', 'CEL') NOT NULL,
    NUMERO		VARCHAR(10)	NOT NULL,
    FK_CLIENTE	INT,
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)  
    );
    
    SHOW TABLES;
    
    DESC ENDERECO;
    
    SELECT * FROM TELEFONE;
    
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F','CLAR@MAIL.COM','5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);