/* SEÇÃO 10 -  EXERCICIO FIXAÇAO DML */
/* EXERCICIOS DML */

USE COMERCIO;

SHOW TABLES;

SELECT * FROM cliente;

INSERT INTO CLIENTE VALUES(NULL,'PAULA','F','paula@gmail.com', '77437493');
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ',7);



INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F','giovana@gmailcom','0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M','lorena@bol.com.br','774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M','eduardo@ig.com.br','54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);

INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

/* CADASTRE TELEFONES PARA OS CLIENTES */


INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',20);

/* RELATORIO GERAL DE TODOS OS CLIENTES /TELEFONE/ENDERECO*/
DESC CLIENTE;
DESC TELEFONE;
DESC ENDERECO;

#PROJEÇÃO 
SELECT C.ID_CLIENTE, C.NOME, C.SEXO, C.E_MAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
#OFIGEM
FROM CLIENTE C 
#JUNÇÃO
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
ORDER BY C.ID_CLIENTE;

/* RELATORIO DE HOMENS */

SELECT C.ID_CLIENTE, C.NOME, C.SEXO, C.E_MAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
#OFIGEM
FROM CLIENTE C 
#JUNÇÃO
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE C.SEXO = 'M'
ORDER BY C.ID_CLIENTE;

/* CLIENTES COM SEXO ERRADO:
	12, 13, 18, 19 */
#UPDATE
UPDATE CLIENTE SET SEXO = 'F' WHERE ID_CLIENTE = 12;
UPDATE CLIENTE SET SEXO = 'F' WHERE ID_CLIENTE = 13;
UPDATE CLIENTE SET SEXO = 'F' WHERE ID_CLIENTE = 18;
UPDATE CLIENTE SET SEXO = 'F' WHERE ID_CLIENTE = 19;

SELECT C.ID_CLIENTE, C.NOME, C.SEXO, C.E_MAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
#OFIGEM
FROM CLIENTE C 
#JUNÇÃO
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE C.SEXO = 'M'
ORDER BY C.ID_CLIENTE;


/* RELATORIO DE MULHERES */

SELECT C.ID_CLIENTE, C.NOME, C.SEXO, C.E_MAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
#OFIGEM
FROM CLIENTE C 
#JUNÇÃO
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE C.SEXO = 'F'
ORDER BY C.ID_CLIENTE;

/* CLIENTES COM SEXO ERRADO:
	16 */
#UPDATE
UPDATE CLIENTE SET SEXO = 'M' WHERE ID_CLIENTE = 16;

SELECT C.ID_CLIENTE, C.NOME, C.SEXO, C.E_MAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
#OFIGEM
FROM CLIENTE C 
#JUNÇÃO
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE C.SEXO = 'F'
ORDER BY C.ID_CLIENTE;

/* QUANTIDADE DE HOMENS E MULHERES */

#PROJEÇÃO
SELECT SEXO, COUNT(*) AS QUANTIDADE
#ORIGEM
FROM CLIENTE
#SELECAO
GROUP BY SEXO;


/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NAO TENHAM CELULAR */
#PROJECAO
SELECT * FROM ENDERECO LIMIT 3;

/* A QUERY DO JEITO QUE FIZEMOS ABAIXO HÁ ERRO, PQ A GIOVANA TEM CELULAR, MAS O FILTRO QUE REALIZAMOS SÓ TROUXE O TIPO COMERCIAL, E NÃO É ISSO QUE QUEREMOS

SELECT C.ID_CLIENTE, C.E_MAIL, C.NOME, E.BAIRRO, E.CIDADE, T.TIPO
#ORIGEM 
FROM CLIENTE C
#JUNÇÃO
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
#SELEÇÃO
WHERE SEXO = 'F'
AND E.BAIRRO = 'CENTRO' AND  E.CIDADE LIKE '%RIO D%'
AND T.TIPO <> 'CEL' ;
*/


/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.E_MAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE T.TIPO = 'CEL'
AND E.ESTADO = 'RJ'


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.E_MAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE C.SEXO = 'F'
AND E.ESTADO = 'SP' AND T.TIPO = 'CEL';