/* SEÇÃO 15 - SUBCONJUNTO DO CONJUNTO */

/* RESPONDA: 

QUAL VENDEDOR QUE VENDEU MENOS EM MARÇO E O SEU NOME
QUAL VENDEDOR QUE VENDEU MAIS EM MARCÇO E SEU NOME
QUAL VENDEDOR VENDEU MAIS QUE A MÉDIA DE FEVEREIRO */

SELECT * FROM VENDEDORES;

SELECT NOME, MARCO AS VALOR 
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

SELECT NOME, MARCO AS VALOR 
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO AS VALOR 
FROM VENDEDORES
WHERE FEVEREIRO >= (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

/* A32 - OPERADORES DE LINHAS

AS FUNÇÕES DE AGREGAÇÃO QUE VIMOS ANTERIORMENTE SÓ FUNCIONAM EM COLUNA 

ABAIXO VEREMOS COMO SOMAR O TOTAL POR VENDEDOR*/

SELECT NOME, (JANEIRO + FEVEREIRO + MARCO) AS 'TOTAL'
FROM VENDEDORES;

SELECT NOME, 
	   JANEIRO,
       FEVEREIRO,
       MARCO,
       (JANEIRO + FEVEREIRO + MARCO) AS 'TOTAL',
              (JANEIRO + FEVEREIRO + MARCO) * 0.25 AS 'DESCONTO',
	   TRUNCATE((JANEIRO + FEVEREIRO + MARCO)/3,2) AS 'MÉDIA'
FROM VENDEDORES;